# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # You can easily switch containers and versions here.
      # @see https://circleci.com/docs/2.0/circleci-images/#php
      # The following container already comes with Apache, Node.js and
      # chromedriver and geckodriver preinstalled.
      - image: circleci/php:7.2-apache-node-browsers
      - image: circleci/mariadb:latest
        environment:
          - MYSQL_ROOT_HOST=%

    working_directory: ~/drupal-circleci-behat

    steps:
      - checkout

      # Setup Apache.
      # For convenience the site will be accessible internally under a
      # *.localhost TLD. Which also is used in the behat.yml.
      - run:
          name: Setup Apache
          command: |
            sudo cp .circleci/env/drupal-circleci-behat.conf /etc/apache2/sites-available/drupal-circleci-behat.conf
            sudo a2ensite drupal-circleci-behat
            sudo service apache2 start
            echo 127.0.0.1 drupal-circleci-behat.localhost | sudo tee -a /etc/hosts

      - run:
          name: Setup tools
          command: |
            sudo apt-get -qq update && sudo apt-get -qqy upgrade
            sudo apt-get -yqq install libpng-dev mariadb-client nano
            sudo docker-php-ext-install gd mbstring mysqli pdo pdo_mysql
            sudo service apache2 restart

      # Restore cache.
      # Cache gets invalidated automatically as soon as the composer.lock has
      # changed between two builds.
      # You can easily invalidate the cache manually by incrementing its key:
      # v2-..., v3-... and so on.
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
            # Fallback to use the latest cache if no exact match is found.
            - v1-dependencies-

      # Install dependencies and add the bin dir to the global $PATH to use its
      # commands without needing to reference their location:
      # Now you can use `drush` instead of `cd web && ../bin/drush` for example.
      - run:
          name: Composer Install
          command: |
            composer install -n --prefer-dist
            echo 'export PATH=$HOME/drupal-circleci-behat/bin:$PATH' >> $BASH_ENV
            source /home/circleci/.bashrc

      # Save the dependencies.
      # This step as all other steps can also get implemented multiple times.
      # Imagine what else you can cache then:
      # - theme dependencies
      # - database dumps (importing an existing database before `drush cim`
      #   will dramatically improve build time when the project gets larger)
      # - ...
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.lock" }}

      # A vanilla Drupal.
      # As soon as your project starts you will need to extend this step:
      # - drush updb
      # - drush cim
      # - ...
      - run:
          name: Setup Drupal
          command: |
            cp .circleci/env/.htaccess web/.htaccess
            cp .circleci/env/settings.local.php web/sites/default/settings.local.php
            cd web
            drush site:install --site-name='Hello World' -y

      # Run tests and store the results to get a nice looking test summary.
      # @see https://circleci.com/docs/2.0/configuration-reference/#store_test_results
      - run:
          name: Tests
          command: |
            mkdir -p tests/test-results/junit
            cd tests/behat
            behat --no-snippets -f pretty -o std -f junit -o ../../test-results/junit/junit.xml
      - store_test_results:
          path: tests/test-results

  # Above commands all belong to the build step. Now comes the deploy step.
  # Which only gets reached when all tests passed.
  #
  # This step absolutely depends on your deployment tactic:
  # - maybe you will SSH upload the build to your servers
  # - maybe you will SSH trigger some deploy script to do the work
  # - ...
  #
  # In this example CircleCI branch-wise SSH into the dev or live server and
  # calls a Bash script which then may run:
  # - bin/drush state:set system.maintenance_mode 1 -y
  # - git pull
  # - composer install
  # - bin/drush updb -y
  # - bin/drush cim -y
  # - ...
  deploy:
    machine:
      enabled: true

    working_directory: ~/drupal-circleci-behat

    steps:
      - checkout
#      - run:
#          name: Fix ssh Could not resolve hostname
#          command: |
#            ssh-keyscan "${LIVE_IP}" >> ~/.ssh/known_hosts
#            ssh-keyscan "${DEV_IP}" >> ~/.ssh/known_hosts
#
#      - add_ssh_keys: # add private SSH key from CircleCI account based on fingerprint
#          fingerprints:
#            - "14:09:a1:b2:b3:c4:d5:e6:f7:g8:h9:81:"
#
#      - run:
#          name: Deploy master
#          command: if [ "${CIRCLE_BRANCH}" == "master" ]; then ssh -p "${LIVE_PORT}" "${LIVE_USER}"@"${LIVE_IP}" "cd /var/www/wordpress-circleci-behat/scripts/deployment && . deploy.sh ${CIRCLE_SHA1}"; else echo "Skipped"; fi
#      - run:
#          name: Deploy dev
#          command: if [ "${CIRCLE_BRANCH}" == "develop" ]; then ssh -p "${DEV_PORT}" "${DEV_USER}"@"${DEV_IP}" "cd /var/www/wordpress-circleci-behat/scripts/deployment && . deploy.sh ${CIRCLE_SHA1}"; else echo "Skipped"; fi
      - run: echo "${CIRCLE_BRANCH}"; echo "${CIRCLE_SHA1}";

# In this example the whole workflow which consists of a build step and a
# deploy step only gets triggered on pushes to the develop branch and the
# master branch.
# Simply remove the filters to have it triggered in every branch (which raises
# the risk that you hit the maximum 1.500 build minutes/month when you only have
# a free plan).
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - develop
                - master
      - deploy:
          requires:
            - build
# You could limit the CI to only be triggered for develop and master branches.
#          filters:
#            branches:
#              only:
#                - develop
#                - master
